name = "discountvouchers"
main = "src/index.mjs"
compatibility_date = "2024-12-16"

[[d1_databases]]
binding = "DB"
database_name = "discountvouchers"
database_id = "c55ed898-d477-433e-a6ae-2355d6b6da43"

[build]
command = "npm install"
